spring:
  profiles:
    active: localhost
  config:
    import: optional:configserver:http://localhost:8888

  application:
    name: find-nonlinked-rc-sudoc
  cloud:
    config:
      profile: localhost