server:
  port: 8888
spring:
  application:
    name: qualinka-ms-spring-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/abes-esr/spring-cloud-config-server.git