server:
  port: 8888
spring:
  application:
    name: spring-config-server
  cloud:
    config:
      server:
        git:
          uri: file://C:/Users/charot/git/qualinka-spring-cloud-config-server