name: "build-test-pub-find-ra-idref-todockerhub"

env:
  DOCKERHUB_IMAGE_PREFIX: abesesr/qualinka-ms
  DIRECTORY: find-ra-idref

on:
  push:
    paths:
      - 'find-ra-idref/**'
  pull_request:
  workflow_dispatch:

jobs:
# find-ra-idref job
  build-test-pubtodockerhub:
    name: Build find-ra-idref
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.DIRECTORY }}

    steps:
      - name: "Build: checkout source code"
        uses: actions/checkout@v3

      - name: "Build: build docker image"
        run: |
          docker build . -t localimage:latest

      - name: "Push: prepare version from git tags/branchs"
        id: docker_tag_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_IMAGE_PREFIX }}

      - name: "Push: login to DockerHub"
        if: github.event_name != 'pull_request'
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: "Push: push docker image"
        if: github.event_name != 'pull_request'
        run: |
          DOCKER_TAGS="${{ steps.docker_tag_meta.outputs.tags }}"
            for DOCKER_TAG in $DOCKER_TAGS
            do
              docker build . --target ${{ env.DIRECTORY }} -t ${DOCKER_TAG}-${{ env.DIRECTORY }}
              docker push ${DOCKER_TAG}-${{ env.DIRECTORY }}
            done